services:
  mini-qr:
    image: ghcr.io/lyqht/mini-qr:latest
    container_name: MiniQR
    restart: always
    ports:
      - 8082:8080
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
