volumes:
  twitchdropsbot_config:
    name: twitchdropsbot_config
  twitchdropsbot_logs:
    name: twitchdropsbot_logs

services:
  twitchdropsbot:
    container_name: TwitchDropsBot
    image: ghcr.io/alorf/twitchdropsbot:latest
    volumes:
      - twitchdropsbot_config:/app/Configuration
      - twitchdropsbot_logs:/app/logs
    environment:
      - ADD_ACCOUNT=false
      - INSIDE_DOCKER=true
    restart: always

