volumes:
  blinko_data:
    name: blinko_data
  blinko-postgres_data:
    name: blinko-postgres_data
    
services:
  blinko-website:
    image: blinkospace/blinko:latest
    container_name: Blinko
    environment:
      NODE_ENV: production
      # NEXTAUTH_URL: http://localhost:1111
      # IMPORTANT: If you want to use sso, you must set NEXTAUTH_URL to your own domain
      # NEXT_PUBLIC_BASE_URL: http://localhost:1111
      # IMPORTANT: Replace this with your own secure secret key!
      # Use `openssl rand -base64 32` in terminal to generate random secure secret key
      NEXTAUTH_SECRET: my_ultra_secure_nextauth_secret
      DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    # Make sure you have enough permissions.
    # volumes:
      # - blinko_data:/app/.blinko 
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 1111:1111
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://blinko-website:1111/"]
      interval: 30s 
      timeout: 10s   
      retries: 5     
      start_period: 30s 

  postgres:
    image: postgres:14
    container_name: BlinkoPostgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      # Use `openssl rand -base64 32` in terminal to generate random PostgreSQL password
      POSTGRES_PASSWORD: mysecretpassword
      TZ: Europe/Berlin
    # Persisting container data
    # Make sure you have enough permissions.
    # volumes:
      # - blinko-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
