volumes:
  memos_data:
    name: memos_data
services:
  memos:
    image: neosmemo/memos:stable
    container_name: Memos
    restart: always
    ports:
      - "5230:5230"
    volumes:
      - memos_data:/var/opt/memos
    environment:
      MEMOS_PORT: 5230
      MEMOS_DRIVER: sqlite
      MEMOS_INSTANCE_URL: https://memos.zzahkaboom24.de
