volumes:
  pocket-id_data:
    name: pocket-id_data

services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2
    restart: always
    env_file: .env
    ports:
      - 1411:1411
    volumes:
      - "pocket-id_data:/app/data"
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
