volumes:
  fireshare_data:
    name: fireshare_data
  fireshare_processed:
    name: fireshare_processed
  fireshare_videos:
    name: fireshare_videos
  fireshare_images:
    name: fireshare_images

services:
  fireshare:
    container_name: Fireshare
    image: shaneisrael/fireshare:1.4.2
    ports:
      - "8383:80"
    volumes:
      - fireshare_data:/data
      - fireshare_processed:/processed
      - fireshare_videos:/videos
      - fireshare_images:/images
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri # For hardware transcoding support
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - MINUTES_BETWEEN_VIDEO_SCANS=5
      # The location in the video thumbnails are generated. A value between 0-100 where 50 would be the frame in the middle of the video file and 0 would be the first frame of the video.
      - THUMBNAIL_VIDEO_LOCATION=0
      # The domain your instance is hosted at. (do not add http or https) e.x: v.fireshare.net, this is required for opengraph to work correctly for shared links. DO NOT SURROUND IN QUOTES.
      - DOMAIN=${DOMAIN}
      - PUID=1000
      - PGID=1000
      - STEAMGRIDDB_API_KEY=${STEAMGRIDDB_API_KEY} # Get a free API key at https://www.steamgriddb.com/profile/preferences/api
      - ENABLE_TRANSCODING=true
      - TRANSCODE_GPU=false

networks:
  nginxproxymanager_default:
    external: true
    name: nginxproxymanager_default
